spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB ?? ??? ????? ??

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: create
